// Generated by Lumier (hash: 2d701ede076e8f9c67464e8b601710f3)
/* eslint-disable */
// @ts-nocheck
/* eslint-disable */
/* prettier-ignore */
/* biome-ignore format: generated file */
/* oxlint-disable */
/// <reference types="@cloudflare/workers-types" />

declare namespace Cloudflare {
  interface Env {
    CACHE: KVNamespace;
    DB: D1Database;
    STAGE: "bachitter";
    UPLOADS: R2Bucket;
  }
}

// Env interface for handler pattern
interface Env extends Cloudflare.Env {}

// Augment cloudflare:workers module for global env access
declare module "cloudflare:workers" {
  // The env object provides typed access to bindings
  const env: Cloudflare.Env;
}

declare global {
  interface CloudflareEnv extends Cloudflare.Env {}
}
